"""empty message

Revision ID: bea9fbb5f737
Revises: 
Create Date: 2023-03-06 10:51:12.801775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea9fbb5f737'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('position_head', sa.String(length=400), nullable=False),
    sa.Column('fio_head', sa.String(length=250), nullable=False),
    sa.Column('mob_position_head', sa.String(length=400), nullable=False),
    sa.Column('mob_fio_head', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=450), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['documents_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('type_expenses', sa.Integer(), nullable=True),
    sa.Column('amounts_ba_to_wars', sa.Numeric(), nullable=True),
    sa.Column('amount_ba_to_mob_tasks', sa.Numeric(), nullable=True),
    sa.Column('total', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amount')
    op.drop_table('documents')
    op.drop_table('organizations')
    op.drop_table('documents_types')
    # ### end Alembic commands ###
